// scripts/evolve/analyze.js
//
// Phase 3.4 — Self-evolving memory: signal → proposal logic.
//
// Pure, deterministic functions. No I/O. Given:
//   - reuse stats (from stats.getReuseStats)
//   - routing-miss stats (from stats.getRoutingMissStats)
//   - the memories themselves (from scripts/memory/store.listAll)
//   - the current routing rule text (string)
//
// Produces a list of structured proposals. Two kinds:
//
//   1) skill-upgrade   — a memory has been surfaced ≥ N times and across
//                        ≥ M distinct sessions → propose creating a draft
//                        SKILL.md from it.
//
//   2) routing-addition — ≥ K substantive prompts cluster on the same token
//                         set without any memory match → propose adding a
//                         new routing entry under the most-likely tier.
//
// Every proposal carries:
//   - id (deterministic given evidence — stable across re-runs)
//   - type
//   - evidence (the raw signal data)
//   - proposal: { kind, target_path, diff (markdown), rationale }
//
// Apply step writes the diff to disk as a draft file the user reviews
// before committing. NEVER auto-applied.
'use strict';

const crypto = require('crypto');

const DEFAULT_REUSE_MIN_COUNT     = 3;
const DEFAULT_REUSE_MIN_SESSIONS  = 2;
const DEFAULT_MISS_MIN_COUNT      = 3;
const DEFAULT_MISS_CLUSTER_MIN    = 2; // distinct prompt-hashes per cluster

// ── helpers ──────────────────────────────────────────────────────────────────

function deterministicId(prefix, payload) {
  const h = crypto.createHash('sha256').update(JSON.stringify(payload)).digest('hex').slice(0, 10);
  return `${prefix}-${h}`;
}

function slugify(s) {
  return String(s || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || 'untitled';
}

// ── skill-upgrade proposals ─────────────────────────────────────────────────

function buildSkillUpgradeMarkdown(memory) {
  const slug = slugify(memory.problem);
  const tags = (memory.tags || []).slice(0, 8);
  const desc = (memory.problem || '').slice(0, 180);
  const approach = (memory.approach || '').trim();
  const lang = memory.language || 'general';

  return [
    '---',
    `name: ${slug}`,
    `description: ${desc.replace(/[\r\n]+/g, ' ')} (auto-derived from memory ${memory.id} after repeated reuse)`,
    `origin: kodelyth-evolve`,
    `language: ${lang}`,
    `tags:`,
    ...tags.map(t => `  - ${t}`),
    '---',
    '',
    `# Skill: ${slug}`,
    '',
    '> **Auto-derived draft.** Generated by `kodelyth-ecc evolve` after this memory was surfaced repeatedly across multiple sessions. Review, refine, and rename before committing.',
    '',
    '## Problem',
    '',
    memory.problem || '_(no problem statement)_',
    '',
    '## Approach',
    '',
    approach || '_(no approach text)_',
    '',
    memory.gotchas?.length ? '## Gotchas\n\n' + memory.gotchas.map(g => `- ${g}`).join('\n') + '\n' : '',
    '## When to invoke',
    '',
    '_Replace this section with explicit trigger conditions. Examples that worked:_',
    '',
    '_(add 2-3 real prompts that historically benefitted from this approach)_',
    '',
    '## Origin',
    '',
    `- Memory id: \`${memory.id}\``,
    `- Captured at: ${memory.captured_at || 'unknown'}`,
    `- Source: ${memory.source || 'unknown'}`,
    `- Auto-promoted by Phase 3.4 self-evolving memory.`,
    '',
  ].filter(Boolean).join('\n');
}

function analyzeReuseForProposals({
  reuseStats,
  memories,
  thresholds: t = {},
} = {}) {
  if (!reuseStats || !Array.isArray(memories)) return [];
  const minCount    = t.minCount    ?? DEFAULT_REUSE_MIN_COUNT;
  const minSessions = t.minSessions ?? DEFAULT_REUSE_MIN_SESSIONS;

  const memoriesById = new Map(memories.map(m => [m.id, m]));
  const proposals = [];

  for (const entry of reuseStats.entries || []) {
    if (entry.count < minCount) continue;
    if ((entry.sessions || []).length < minSessions) continue;
    const memory = memoriesById.get(entry.id);
    if (!memory) continue;

    const targetPath = `skills/${slugify(memory.problem)}/SKILL.md`;
    const evidence = {
      memoryId:    entry.id,
      reuseCount:  entry.count,
      sessions:    entry.sessions,
      projects:    entry.projects || [],
      firstSurfaced: entry.firstSurfaced,
      lastSurfaced:  entry.lastSurfaced,
    };
    proposals.push({
      id:    deterministicId('skill', evidence),
      type:  'skill-upgrade',
      evidence,
      proposal: {
        kind:        'create-skill',
        target_path: targetPath,
        diff:        buildSkillUpgradeMarkdown(memory),
        rationale:
          `Memory "${memory.problem}" surfaced ${entry.count}x across ` +
          `${(entry.sessions || []).length} sessions — promoting to a draft skill.`,
      },
    });
  }
  return proposals;
}

// ── routing-addition proposals ──────────────────────────────────────────────

const STOP = new Set([
  'the','a','an','to','of','in','on','for','and','or','but','if','is','are',
  'was','were','be','been','have','has','had','do','does','did','this','that',
  'it','its','i','you','we','they','my','your','our','can','will','should',
  'how','what','why','when','where','use','using','run','make','need','want',
]);

function topTokens(tokens, k = 4) {
  const filtered = (tokens || []).filter(t => t.length >= 3 && !STOP.has(t));
  return filtered.slice(0, k);
}

/**
 * Cluster routing-miss entries by their top-K tokens. Two entries are in
 * the same cluster if their top-K token sets share at least 2 tokens.
 * Greedy / O(n²) — fine for thousands of misses, this isn't BM25.
 */
function clusterMisses(missEntries) {
  const clusters = [];
  for (const m of missEntries) {
    const myTokens = topTokens(m.tokens);
    if (myTokens.length === 0) continue;
    let placed = false;
    for (const c of clusters) {
      const overlap = myTokens.filter(t => c.tokens.has(t)).length;
      if (overlap >= 2) {
        c.entries.push(m);
        c.count += m.count;
        myTokens.forEach(t => c.tokens.add(t));
        placed = true;
        break;
      }
    }
    if (!placed) {
      clusters.push({
        tokens:  new Set(myTokens),
        entries: [m],
        count:   m.count,
      });
    }
  }
  return clusters
    .map(c => ({
      tokens:  [...c.tokens],
      entries: c.entries,
      count:   c.count,
    }))
    .sort((a, b) => b.count - a.count);
}

function buildRoutingProposalMarkdown(cluster) {
  const sampleTokens = cluster.tokens.slice(0, 4).join(' / ');
  const sampleLines = cluster.entries
    .flatMap(e => e.samples || [])
    .slice(0, 5)
    .map(s => `  - "${s.replace(/\n/g, ' ').slice(0, 140)}"`)
    .join('\n');
  return [
    '<!-- proposed addition to rules/common/agent-intent-routing.md -->',
    '<!-- review by hand, decide on tier + agent, then merge -->',
    '',
    `### TODO-agent — covers prompts about ${sampleTokens}`,
    '',
    `Trigger if the user mentions ${cluster.tokens.slice(0, 6).map(t => `\`${t}\``).join(', ')}.`,
    '',
    '| Signal | Real human phrasing |',
    '|---|---|',
    `| repeated unrouted prompt cluster | ${cluster.tokens.slice(0, 5).join(', ')} |`,
    '',
    `**Origin:** Phase 3.4 self-evolving memory \u2014 ${cluster.count} prompts in this cluster were submitted with no memory match and (presumably) no specialist routing.`,
    '',
    'Recent samples:',
    sampleLines || '  _(none)_',
    '',
    '_(Pick the right tier in `rules/common/agent-intent-routing.md` before merging. Do NOT commit this block as-is — replace `TODO-agent` with the real agent name and slot under the correct priority tier.)_',
    '',
  ].join('\n');
}

function analyzeMissesForProposals({
  missStats,
  thresholds: t = {},
} = {}) {
  if (!missStats) return [];
  const minCount      = t.minCount      ?? DEFAULT_MISS_MIN_COUNT;
  const minClusterDistinct = t.minClusterDistinct ?? DEFAULT_MISS_CLUSTER_MIN;

  const clusters = clusterMisses(missStats.entries || []);
  const proposals = [];

  for (const c of clusters) {
    if (c.count < minCount) continue;
    if (c.entries.length < minClusterDistinct) continue;
    const evidence = {
      tokens:           c.tokens,
      occurrences:      c.count,
      distinct_prompts: c.entries.length,
      sample_prompts:   c.entries.flatMap(e => e.samples || []).slice(0, 5),
    };
    proposals.push({
      id:    deterministicId('route', { tokens: c.tokens.sort() }),
      type:  'routing-addition',
      evidence,
      proposal: {
        kind:        'add-routing-entry',
        target_path: 'rules/common/agent-intent-routing.md',
        diff:        buildRoutingProposalMarkdown(c),
        rationale:
          `${c.count} substantive prompts (${c.entries.length} distinct) clustered on ` +
          `tokens [${c.tokens.slice(0, 4).join(', ')}] without any memory match. ` +
          `Likely a routing gap.`,
      },
    });
  }
  return proposals;
}

// ── single entry point ──────────────────────────────────────────────────────

function analyzeAll({
  reuseStats,
  missStats,
  memories,
  thresholds = {},
} = {}) {
  return [
    ...analyzeReuseForProposals({
      reuseStats,
      memories: memories || [],
      thresholds: {
        minCount:    thresholds.reuseMinCount,
        minSessions: thresholds.reuseMinSessions,
      },
    }),
    ...analyzeMissesForProposals({
      missStats,
      thresholds: {
        minCount:           thresholds.missMinCount,
        minClusterDistinct: thresholds.missMinClusterDistinct,
      },
    }),
  ];
}

module.exports = {
  DEFAULT_REUSE_MIN_COUNT,
  DEFAULT_REUSE_MIN_SESSIONS,
  DEFAULT_MISS_MIN_COUNT,
  DEFAULT_MISS_CLUSTER_MIN,
  analyzeReuseForProposals,
  analyzeMissesForProposals,
  analyzeAll,
  buildSkillUpgradeMarkdown,
  buildRoutingProposalMarkdown,
  clusterMisses,
  _internals: { topTokens, slugify, deterministicId },
};
